# Importing necessary libraries
import os
import asyncio
from dotenv import load_dotenv

# Import agent library from autogen
from autogen_agentchat.agents import AssistantAgent

# Import group chat and termination conditions
from autogen_agentchat.teams import SelectorGroupChat
from autogen_agentchat.conditions import TextMentionTermination, MaxMessageTermination

# Import message types
from autogen_agentchat.messages import TextMessage

# Import Console for streaming output
from autogen_agentchat.ui import Console

# Import OpenAI client from autogen_ext
from autogen_ext.models.openai import OpenAIChatCompletionClient

# Load environment variables
load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Create the model client
model_client = OpenAIChatCompletionClient(
    model="gpt-4o-mini",
    api_key=OPENAI_API_KEY
)

# ──────────────────────────────────────────────
# Create Agents
# ──────────────────────────────────────────────

# Manager Agent
manager_agent = AssistantAgent(
    name="Manager",
    description="A marketing campaign manager who provides campaign topics, evaluates ideas and scripts, and makes final decisions.",
    system_message="""You are a marketing campaign manager. Your role is to:
    1. Provide campaign topics to the creative team.
    2. Evaluate the ideas and scripts generated by the team.
    3. Select the best idea and ask the Script Writer to develop it.
    4. Ask the Script Reviewer to review the script.
    5. Make a final decision on whether the script is ready for production.
    
    When you are satisfied with the final script, end your message with the word APPROVED.
    If revisions are needed, specify the key areas to address.
    """,
    model_client=model_client,
)

# Idea Generation Agent
idea_generation_agent = AssistantAgent(
    name="Idea_Generator",
    description="A creative marketing expert who generates innovative campaign ideas, storylines, and characters for video content.",
    system_message="""You are a creative marketing expert. Your role is to:
    1. Generate innovative campaign ideas based on the given topic.
    2. Suggest potential storylines and characters for video content.
    3. Provide a brief outline for each idea.
    Present 3-5 unique ideas for each request.
    """,
    model_client=model_client,
)

# Script Writer Agent
script_writer_agent = AssistantAgent(
    name="Script_Writer",
    description="An expert script writer for marketing videos who develops full scripts with dialogue, scene descriptions, and camera directions.",
    system_message="""You are an expert script writer for marketing videos. Your role is to:
    1. Develop full scripts based on the campaign ideas provided.
    2. Include dialogue, scene descriptions, and camera directions.
    3. Ensure the script aligns with the campaign objectives and target audience.
    Aim for scripts of 2-3 minutes in length.
    """,
    model_client=model_client,
)

# Script Reviewer Agent
script_reviewer_agent = AssistantAgent(
    name="Script_Reviewer",
    description="A critical and detail-oriented script reviewer who analyzes scripts for effectiveness, engagement, and alignment with campaign goals.",
    system_message="""You are a critical and detail-oriented script reviewer. Your role is to:
    1. Analyze scripts for effectiveness, engagement, and alignment with campaign goals.
    2. Provide constructive feedback on dialogue, pacing, and overall structure.
    3. Suggest improvements or alternatives where necessary.
    4. Ensure the script adheres to brand guidelines and target audience preferences.
    Be thorough and specific in your feedback.
    """,
    model_client=model_client,
)

# ──────────────────────────────────────────────
# Define the Conversation Flow
# ──────────────────────────────────────────────

# The exact turn order after the Manager's initial task message
TURN_ORDER = [
    "Idea_Generator",    # Turn 0: Idea Generator responds to Manager's brief
    "Manager",           # Turn 1: Manager evaluates ideas and picks one
    "Script_Writer",     # Turn 2: Script Writer develops the selected idea
    "Manager",           # Turn 3: Manager forwards script for review
    "Script_Reviewer",   # Turn 4: Script Reviewer provides feedback
    "Manager",           # Turn 5: Manager makes final decision (APPROVED or revisions)
]


def workflow_selector(messages):
    """Custom selector that enforces a fixed conversation sequence."""
    turn = len(messages) - 1  # Subtract 1 for the initial task message
    if turn < len(TURN_ORDER):
        return TURN_ORDER[turn]
    return None  # End if we exceed the turn order


# ──────────────────────────────────────────────
# Create the Group Chat Team
# ──────────────────────────────────────────────

# Termination conditions
termination = TextMentionTermination("APPROVED") | MaxMessageTermination(10)

# Create the team
team = SelectorGroupChat(
    participants=[manager_agent, idea_generation_agent, script_writer_agent, script_reviewer_agent],
    model_client=model_client,
    selector_func=workflow_selector,
    termination_condition=termination,
    allow_repeated_speaker=True,
)

# ──────────────────────────────────────────────
# Run the Workflow
# ──────────────────────────────────────────────

async def main():
    # The Manager's opening message — passed as TextMessage so source="Manager"
    task = TextMessage(
        content=(
            "Hello team, I need creative ideas for our new marketing campaign. "
            "Our product is eco-friendly water bottles. "
            "Could you generate 3-5 innovative campaign ideas, including potential "
            "storylines and characters for video content?"
        ),
        source="Manager",
    )

    # Run and stream the conversation to the console
    result = await Console(team.run_stream(task=task))

    # Print the final summary
    print("\n" + "=" * 60)
    print("WORKFLOW COMPLETE")
    print("=" * 60)

    # Print each message summary
    for message in result.messages:
        print(f"\n[{message.source}]:")
        #rint(message.content[:200] + "..." if len(message.content) > 200 else message.content)
        #rint("-" * 50)


# Entry point
if __name__ == "__main__":
    asyncio.run(main())
